name: Bug report
description: Report a bug
labels: ["bug"]
body:
  - type: textarea
    id: steps
    attributes: {label: Steps to reproduce, placeholder: "1. ..., 2. ..."}
    validations: {required: true}
  - type: textarea
    id: expected
    attributes: {label: Expected}
  - type: textarea
    id: actual
    attributes: {label: Actual}
  - type: textarea
    id: env
    attributes: {label: Env, placeholder: "OS, Python, Node, Java"}

