name: Feature request
description: Propose an improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes: {label: Problem}
  - type: textarea
    id: proposal
    attributes: {label: Proposal}
  - type: textarea
    id: alt
    attributes: {label: Alternatives}

