name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build and Publish Release
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine setuptools wheel
      
      - name: Create setup.py
        run: |
          cat > setup.py << 'EOF'
          from setuptools import setup, find_packages
          
          with open("README.md", "r", encoding="utf-8") as fh:
              long_description = fh.read()
          
          setup(
              name="applied-probability-framework",
              version="1.0.0",
              author="Framework Contributors",
              description="Professional Monte Carlo simulation framework for probability analysis",
              long_description=long_description,
              long_description_content_type="text/markdown",
              url="https://github.com/yourusername/applied-probability-framework",
              packages=find_packages(where="src/python"),
              package_dir={"": "src/python"},
              classifiers=[
                  "Development Status :: 4 - Beta",
                  "Intended Audience :: Science/Research",
                  "Topic :: Scientific/Engineering :: Mathematics",
                  "License :: OSI Approved :: MIT License",
                  "Programming Language :: Python :: 3",
                  "Programming Language :: Python :: 3.8",
                  "Programming Language :: Python :: 3.9",
                  "Programming Language :: Python :: 3.10",
                  "Programming Language :: Python :: 3.11",
              ],
              python_requires=">=3.8",
              install_requires=[
                  "numpy>=1.20.0",
                  "scipy>=1.7.0",
                  "pandas>=1.3.0",
                  "matplotlib>=3.3.0",
              ],
              entry_points={
                  "console_scripts": [
                      "apf=cli:main",
                  ],
              },
          )
          EOF
      
      - name: Build package
        run: |
          python -m build
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

